version: '3'

services:
  app:
    image: mlops_sp
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://user:password@db:5432/mydb"

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    volumes:
      - pgdata
