[file_path]
raw_txt = 'data/corpus.txt'
cleaned_csv = 'data/comments.csv'
model_path = 'model/model_1'

[postgres_dev]
database = 'dev'
host = '127.0.0.1'
port = 5432
user = 'postgres'
pw = '123456'

[model]
seed_num = 1234
