[file_path]
data_dir = 'data/'
model_path = 'model/model_1'

[postgres_dev]
database = 'dev'
host = '127.0.0.1'
port = 5432
user = 'postgres'
pw = '123456'

[data]
version = 'v001'

[model]
seed_num = 1234
